[tool.poetry]
name = "PJATK-SUML"
version = "0.1.0"
description = "Demonstrates"
authors = ["jaroslaw.malucha@gmail.com"]

[tool.poetry.dependencies]
python = "3.11.*"
streamlit = "*"
tensorflow = "*"
pandas = "*"
numpy = "*"
